### ISSUE TITLE
没找到新增流程的入口,不知道是否是我粗心

### ISSUE THREAD

**Issue by 0xblack** [leooneone/aibpm.plus#1]
如题,希望作者指点一下

**Comment by leooneone** [comment]
因为不希望新增太多流程，所以没有配置新增权限，如需要可以在权限配置配置，新增也可以通过修改已有流程模板的名称来实现，名称不同系统就会认为是新增

0xblack ***@***.***> 於 2023年11月8日 週三 上午10:07寫道：

**Comment by leooneone** [comment]
因为不希望新增太多流程，所以没有配置新增权限，如需要可以在权限配置配置，新增也可以通过修改已有流程模板的名称来实现，名称不同系统也会认为是新增
